log_file: 'log.txt'

event_handler:
  ignored_msgtypes: ['SYNC_STARTED', 'SYNC_STARTED', 'SYNC_ENDED']
  omm_msgtypes: ['UPDATE_EXTENSION', 'DELETE_EXTENSION', 'RENAME_EXTENSION', 'UNSUBSCRIBE_DEVICE']
  asterisk_msgtypes: []

guru3:
  host: 10.43.42.10
  port: 8086
  token_file: guru3.tk
  tls: false

omm:
  host: 10.40.42.55
  port: 12622
  token_file: omm.tk

asterisk:
  host: 10.43.42.10
  port: 5432
  token_file: asterisk.tk