log_file: 'log.txt'

event_handler:
  omm_msgtypes: ['UPDATE_EXTENSION', 'DELETE_EXTENSION', 'UPDATE_CALLGROUP', 'RENAME_EXTENSION', 'UNSUBSCRIBE_DEVICE']
  asterisk_msgtypes: []

guru3:
  #host: 'guru3.hackwerk.fun'
  host: 10.43.42.10
  port: 8086
  token_file: 'guru3.tk'
  tls: false

omm:
  host: '10.40.42.55'
  port: 12622
  token_file: 'omm.tk'