log_file: 'log.txt'

event_handler:
  # ALL MESSAGE TYPES:
  #  SYNC_STARTED
  #  SYNC_ENDED
  #  UPDATE_EXTENSION
  #  DELETE_EXTENSION
  #  UPDATE_CALLGROUP
  #  RENAME_EXTENSION
  #  UNSUBSCRIBE_DEVICE
  ignored_msgtypes: ['SYNC_STARTED', 'SYNC_ENDED', 'UPDATE_CALLGROUP']
  collect_ppns_interval: 10

guru3:
  host: guru3.hackwerk.fun
  port: 443
  password_env: GURU_PW
  tls: true

omm:
  host: 10.43.42.55
  port: 12622
  username: omm
  password_env: OMM_PW

asterisk:
  host: 10.43.42.10
  port: 5432
  username: asterisk
  password_env: ASTERISK_PW
  password_length: 10
  temp_num_length: 5

registration:
  port: 4242