log_file: 'log.txt'

event_handler:
  # ALL MESSAGE TYPES:
  #  SYNC_STARTED
  #  SYNC_ENDED
  #  UPDATE_EXTENSION
  #  DELETE_EXTENSION
  #  UPDATE_CALLGROUP
  #  RENAME_EXTENSION
  #  UNSUBSCRIBE_DEVICE
  ignored_msgtypes: ['SYNC_STARTED', 'SYNC_ENDED', 'UPDATE_CALLGROUP']
  collect_ppns_interval: 10

guru3:
  host: 10.43.42.10
  port: 8086
  token_file: secrets/guru3.tk
  tls: false

omm:
  host: 10.43.42.55
  port: 12622
  token_file: secrets/omm.tk

asterisk:
  host: 10.43.42.10
  port: 5432
  token_file: secrets/asterisk.tk
  password_length: 10

registration:
  port: 4242
  public: false
